changes: minor bug fixes.
KonoTyran/Slay-The-Spire-Archipelago-Mod pull request #3
Opened 2023-01-02 21:11 UTC by BloodySw

- top bar icon no longer clickable when a room is not completed and between acts
- top bar icon is now greyed out when it's not possible to open it
- number next to top bar icon now shows number of items received since you last opened it (also now shows correct amount instead of 0 when connecting)
- boss relics rewards can now be opened and closed as many times as needed without consuming the reward (until a boss relic is chosen)
- the previous screen will now be closed upon opening the Archipelago reward screen, returning to "null"/battle screen (small bug - the game now softlocks between acts. Band-aid fix by making it impossible to open between acts: on room -1 when act>1)
- boss chest now no longer opens the reward screen. The location is sent upon entering the room anyway. Removing the boss chest reward screen fixes the crash when using controller support (game was trying to place the cursor on the first item in an empty list)

2023-01-02 22:49 UTC, KonoTyran commented
I know this fixes #2 this this affect #1 at all?

2023-01-03 14:15 UTC, BloodySw commented
The game seems to have several hardcoded situations where triggering them, changes the room phase to "competed" (thus showing the "proceed" arrow and making it possible to move to the next room). This seems to happen when consuming rare card draw or when obtaining certain relics, such as bottled flame/lighting/tornado. Because the reward screen is now only openable when room is already completed, it should fix the "autocompleting" issue.

2023-01-04 16:50 UTC, KonoTyran requested changes
If desired, you could also add your name to `src/main/resources/ModTheSpire.json` and `AUTHOR` in `src/main/java/ArchipelagoMW/ArchipelagoMW.java`

2023-01-04 16:50 UTC, KonoTyran commented on src/main/java/ArchipelagoMW/patches/TopPanelPatch.java
> +        if(AbstractDungeon.getCurrRoom().phase != AbstractRoom.RoomPhase.COMPLETE || (AbstractDungeon.getCurrMapNode().y == -1 && AbstractDungeon.actNum != 1)){
this should be above the draw function above and you should just set the color there instead of setting the color and redrawing the icon on top of what was already there.

2023-01-05 02:07 UTC, BloodySw commented
I think I added the change requested?I'm not sure

2023-01-05 15:50 UTC, KonoTyran approved these changes

2023-01-05 15:52 UTC, merged